// Converts the raw menu CSV into typed data:
//   src/data/menu.generated.ts         the whole menu (for the menu page)
//   src/data/home-dishes.generated.ts  only the dishes in home-selection.ts
// Usage: npm run import:menu
// Names, descriptions and prices are kept exactly as published (spelling included).
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const csvPath = `${root}eddys-cafe-assets/05-Menu-Data/menu.csv`
const outPath = `${root}src/data/menu.generated.ts`
const homeOutPath = `${root}src/data/home-dishes.generated.ts`
// Node runs this TypeScript file directly (type stripping); it has no imports.
const { homeSelection } = await import(new URL('../src/data/home-selection.ts', import.meta.url))

function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let quoted = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') {
        field += '"'
        i++
      } else if (c === '"') quoted = false
      else field += c
    } else if (c === '"') quoted = true
    else if (c === ',') {
      row.push(field)
      field = ''
    } else if (c === '\n' || c === '\r') {
      if (c === '\r' && text[i + 1] === '\n') i++
      row.push(field)
      rows.push(row)
      row = []
      field = ''
    } else field += c
  }
  if (field || row.length) {
    row.push(field)
    rows.push(row)
  }
  return rows.filter((r) => r.length > 1)
}

const slug = (value) =>
  value
    .toLowerCase()
    .replace(/['’]\s*/g, '') // "Eddy' s Khaas" (as published) → "eddys-khaas"
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

function parsePrice(text) {
  const from = /^from\s/i.test(text.trim())
  const amount = Number(text.replace(/[^0-9]/g, ''))
  if (!Number.isFinite(amount) || amount <= 0) throw new Error(`Bad price: ${text}`)
  return { amount, from }
}

const [header, ...rows] = parseCsv(readFileSync(csvPath, 'utf8').replace(/^\uFEFF/, ''))
const col = Object.fromEntries(header.map((name, index) => [name, index]))

const nameCounts = new Map()
for (const r of rows)
  nameCounts.set(r[col['Item Name']], (nameCounts.get(r[col['Item Name']]) ?? 0) + 1)

const categories = []
const items = rows.map((r) => {
  const name = r[col['Item Name']].trim()
  const category = r[col.Category].trim()
  if (!categories.includes(category)) categories.push(category)
  const { amount, from } = parsePrice(r[col.Price])
  const file = r[col['Image Filename']].trim()
  const type = r[col['Image Type']]
  const id = nameCounts.get(name) > 1 ? `${slug(category)}-${slug(name)}` : slug(name)
  return {
    id,
    name,
    description: r[col.Description].trim(),
    price: amount,
    ...(from ? { priceFrom: true } : {}),
    category,
    section: r[col.Section].trim() === 'Drink' ? 'drink' : 'food',
    image: {
      alt: name,
      ...(file.includes('/')
        ? {
            source: file,
            sourceKind: /Restaurant's own|Google Maps/i.test(type) ? 'own' : 'reference',
          }
        : {}),
    },
  }
})

const ids = new Set()
for (const item of items) {
  if (ids.has(item.id)) throw new Error(`Duplicate id: ${item.id}`)
  ids.add(item.id)
}

const output = `// Generated by scripts/import-menu.mjs from eddys-cafe-assets/05-Menu-Data/menu.csv.
// Do not edit by hand: re-run \`npm run import:menu\`. Spelling is as published.
import type { MenuItem } from './menu'

export const menuCategories = ${JSON.stringify(categories, null, 2)} as const

export const menuItems: readonly MenuItem[] = ${JSON.stringify(items, null, 2)}
`
writeFileSync(outPath, output)
console.log(
  `Wrote ${String(items.length)} items in ${String(categories.length)} categories to src/data/menu.generated.ts`,
)

// Home page subset, so the home bundle doesn't carry the whole menu.
const byId = new Map(items.map((item) => [item.id, item]))
const homeIds = [...new Set(Object.values(homeSelection).flat())]
const missing = homeIds.filter((id) => !byId.has(id))
if (missing.length) throw new Error(`home-selection.ts has unknown ids: ${missing.join(', ')}`)
const homeDishes = Object.fromEntries(homeIds.map((id) => [id, byId.get(id)]))

writeFileSync(
  homeOutPath,
  `// Generated by scripts/import-menu.mjs: the dishes listed in home-selection.ts.
// Do not edit by hand: re-run \`npm run import:menu\`. Spelling is as published.
import type { MenuItem } from './menu'

export const homeDishes: Readonly<Record<string, MenuItem>> = ${JSON.stringify(homeDishes, null, 2)}
`,
)
console.log(`Wrote ${String(homeIds.length)} home dishes to src/data/home-dishes.generated.ts`)
