// Generated by scripts/import-menu.mjs: each menu item's raw photo in eddys-cafe-assets/.
// "own" is the café's own photo; "reference" is a watermarked foodpanda stand-in.
// Build-time reference for choosing photos; the site doesn't import it.
import type { ImageAsset } from './images'

export const menuImageSources: Readonly<
  Record<string, Required<Pick<ImageAsset, 'source' | 'sourceKind'>>>
> = {
  'fatoush-salad': {
    source: '03-Food-Images/fatoush-salad.jpg',
    sourceKind: 'reference',
  },
  'hummus-with-chicken': {
    source: '03-Food-Images/hummus-with-chicken.jpg',
    sourceKind: 'reference',
  },
  'hummus-with-lamb': {
    source: '03-Food-Images/hummus-with-lamb.jpg',
    sourceKind: 'reference',
  },
  'jooje-pockets': {
    source: '03-Food-Images/jooje-pockets.jpg',
    sourceKind: 'reference',
  },
  'lamb-pockets': {
    source: '03-Food-Images/lamb-pockets.jpg',
    sourceKind: 'reference',
  },
  'hot-and-sour-soup': {
    source: '03-Food-Images/hot-and-sour-soup.jpg',
    sourceKind: 'reference',
  },
  'thai-chicken-soup': {
    source: '03-Food-Images/thai-chicken-soup.jpg',
    sourceKind: 'reference',
  },
  'eddys-special-soup': {
    source: '03-Food-Images/eddys-special-soup.jpg',
    sourceKind: 'reference',
  },
  'roasted-tomato-soup': {
    source: '03-Food-Images/roasted-tomato-soup.jpg',
    sourceKind: 'reference',
  },
  'seafood-chowder-soup': {
    source: '03-Food-Images/seafood-chowder-soup.jpg',
    sourceKind: 'reference',
  },
  'soup-of-the-day': {
    source: '03-Food-Images/soup-of-the-day.jpg',
    sourceKind: 'reference',
  },
  'special-club-sandwich': {
    source: '03-Food-Images/special-club-sandwich.jpg',
    sourceKind: 'reference',
  },
  'croissant-chicken-grilled-sandwich': {
    source: '03-Food-Images/croissant-chicken-grilled-sandwich.jpg',
    sourceKind: 'reference',
  },
  'croissant-egg-and-shroom-sandwich': {
    source: '03-Food-Images/croissant-egg-and-shroom-sandwich.jpg',
    sourceKind: 'reference',
  },
  'open-face-mediterranean-sandwich': {
    source: '03-Food-Images/open-face-mediterranean-sandwich.jpg',
    sourceKind: 'reference',
  },
  'roasted-beef-sandwich': {
    source: '03-Food-Images/roasted-beef-sandwich.jpg',
    sourceKind: 'reference',
  },
  'eddys-katsu-club-sandwich': {
    source: '03-Food-Images/eddys-katsu-club-sandwich.jpg',
    sourceKind: 'own',
  },
  'beef-smash-burger': {
    source: '03-Food-Images/beef-smash-burger.jpg',
    sourceKind: 'reference',
  },
  'chicken-butter-milk-burger': {
    source: '03-Food-Images/chicken-butter-milk-burger.jpg',
    sourceKind: 'reference',
  },
  'sichuan-burger': {
    source: '03-Food-Images/sichuan-burger.jpg',
    sourceKind: 'reference',
  },
  'beef-cheese-burger': {
    source: '03-Food-Images/beef-cheese-burger.jpg',
    sourceKind: 'reference',
  },
  'grilled-chicken-burger': {
    source: '03-Food-Images/grilled-chicken-burger.jpg',
    sourceKind: 'reference',
  },
  'chicken-spicy-moroccan-steak': {
    source: '03-Food-Images/chicken-spicy-moroccan-steak.jpg',
    sourceKind: 'own',
  },
  'beef-spicy-moroccan-steak': {
    source: '03-Food-Images/beef-spicy-moroccan-steak.jpg',
    sourceKind: 'reference',
  },
  'chicken-jalapaeno-steak': {
    source: '03-Food-Images/chicken-jalapaeno-steak.jpg',
    sourceKind: 'reference',
  },
  'beef-jalapaeno-steak': {
    source: '03-Food-Images/beef-jalapaeno-steak.jpg',
    sourceKind: 'reference',
  },
  'chicken-mexican-steak': {
    source: '03-Food-Images/chicken-mexican-steak.jpg',
    sourceKind: 'reference',
  },
  'beef-mexican-steak': {
    source: '03-Food-Images/beef-mexican-steak.jpg',
    sourceKind: 'reference',
  },
  'chicken-americano-steak': {
    source: '03-Food-Images/chicken-americano-steak.jpg',
    sourceKind: 'reference',
  },
  'beef-americano-steak': {
    source: '03-Food-Images/beef-americano-steak.jpg',
    sourceKind: 'reference',
  },
  'chicken-black-pepper-cheese-steak': {
    source: '03-Food-Images/chicken-black-pepper-cheese-steak.jpg',
    sourceKind: 'reference',
  },
  'beef-black-pepper-cheese-steak': {
    source: '03-Food-Images/beef-black-pepper-cheese-steak.jpg',
    sourceKind: 'reference',
  },
  'chicken-italian-mushroom-steak': {
    source: '03-Food-Images/chicken-italian-mushroom-steak.jpg',
    sourceKind: 'reference',
  },
  'beef-italian-mushroom-steak': {
    source: '03-Food-Images/beef-italian-mushroom-steak.jpg',
    sourceKind: 'reference',
  },
  'margherita-pizza': {
    source: '03-Food-Images/margherita-pizza.jpg',
    sourceKind: 'reference',
  },
  'short-ribs-pizza': {
    source: '03-Food-Images/short-ribs-pizza.jpg',
    sourceKind: 'reference',
  },
  'firenze-nova-pizza': {
    source: '03-Food-Images/firenze-nova-pizza.jpg',
    sourceKind: 'reference',
  },
  'chicken-chilli-cheese-pizza': {
    source: '03-Food-Images/chicken-chilli-cheese-pizza.jpg',
    sourceKind: 'own',
  },
  'porcini-pizza': {
    source: '03-Food-Images/porcini-pizza.jpg',
    sourceKind: 'reference',
  },
  'chicken-pepperoni-pizza': {
    source: '03-Food-Images/chicken-pepperoni-pizza.jpg',
    sourceKind: 'reference',
  },
  'beef-pepperoni-pizza': {
    source: '03-Food-Images/beef-pepperoni-pizza.jpg',
    sourceKind: 'reference',
  },
  'pinza-pizza': {
    source: '03-Food-Images/pinza-pizza.jpg',
    sourceKind: 'reference',
  },
  'hot-chicken-bao': {
    source: '03-Food-Images/hot-chicken-bao.jpg',
    sourceKind: 'reference',
  },
  'smash-x-bao': {
    source: '03-Food-Images/smash-x-bao.jpg',
    sourceKind: 'reference',
  },
  'katsu-chicken-bao': {
    source: '03-Food-Images/katsu-chicken-bao.jpg',
    sourceKind: 'reference',
  },
  'chicken-ala-kiev': {
    source: '03-Food-Images/chicken-ala-kiev.jpg',
    sourceKind: 'reference',
  },
  'chicken-schnitzel': {
    source: '03-Food-Images/chicken-schnitzel.jpg',
    sourceKind: 'reference',
  },
  'teriyaki-bowl': {
    source: '03-Food-Images/teriyaki-bowl.jpg',
    sourceKind: 'reference',
  },
  'grilled-chicken-with-hummus': {
    source: '03-Food-Images/grilled-chicken-with-hummus.jpg',
    sourceKind: 'reference',
  },
  'chicken-with-lemon-caper-sauce': {
    source: '03-Food-Images/chicken-with-lemon-caper-sauce.jpg',
    sourceKind: 'reference',
  },
  'mediterranean-grilled-fish': {
    source: '03-Food-Images/mediterranean-grilled-fish.jpg',
    sourceKind: 'reference',
  },
  'baked-chicken-pot': {
    source: '03-Food-Images/baked-chicken-pot.jpg',
    sourceKind: 'reference',
  },
  'nashville-chicken': {
    source: '03-Food-Images/nashville-chicken.jpg',
    sourceKind: 'reference',
  },
  'parmesan-crusted-chicken': {
    source: '03-Food-Images/parmesan-crusted-chicken.jpg',
    sourceKind: 'reference',
  },
  'jalapeno-orange-chicken': {
    source: '03-Food-Images/jalapeno-orange-chicken.jpg',
    sourceKind: 'reference',
  },
  'grilled-chicken-with-sundried-tomato': {
    source: '03-Food-Images/grilled-chicken-with-sundried-tomato.jpg',
    sourceKind: 'reference',
  },
  'fish-and-chips': {
    source: '03-Food-Images/fish-and-chips.jpg',
    sourceKind: 'reference',
  },
  'red-curry-with-garlic-rice': {
    source: '03-Food-Images/red-curry-with-garlic-rice.jpg',
    sourceKind: 'reference',
  },
  'prawn-curry-with-masala-rice': {
    source: '03-Food-Images/prawn-curry-with-masala-rice.jpg',
    sourceKind: 'reference',
  },
  'chicken-cashew-nut': {
    source: '03-Food-Images/chicken-cashew-nut.jpg',
    sourceKind: 'own',
  },
  'stogonuf-chicken-with-garlic-rice': {
    source: '03-Food-Images/stogonuf-chicken-with-garlic-rice.jpg',
    sourceKind: 'reference',
  },
  'dragon-chicken-with-egg-fried-rice': {
    source: '03-Food-Images/dragon-chicken-with-egg-fried-rice.jpg',
    sourceKind: 'reference',
  },
  'oyster-chicken-with-garlic-rice': {
    source: '03-Food-Images/oyster-chicken-with-garlic-rice.jpg',
    sourceKind: 'reference',
  },
  'seven-leaves-with-garlic-rice': {
    source: '03-Food-Images/seven-leaves-with-garlic-rice.jpg',
    sourceKind: 'reference',
  },
  'chicken-chilli-dry': {
    source: '03-Food-Images/chicken-chilli-dry.jpg',
    sourceKind: 'reference',
  },
  'beef-chilli-dry': {
    source: '03-Food-Images/beef-chilli-dry.jpg',
    sourceKind: 'reference',
  },
  'fish-curry-almond-with-masala-rice': {
    source: '03-Food-Images/fish-curry-almond-with-masala-rice.jpg',
    sourceKind: 'reference',
  },
  'kong-pao-chicken-with-egg-fried-rice': {
    source: '03-Food-Images/kong-pao-chicken-with-egg-fried-rice.jpg',
    sourceKind: 'reference',
  },
  'kamil-jooje': {
    source: '03-Food-Images/kamil-jooje.jpg',
    sourceKind: 'reference',
  },
  'shish-tauk-turkish': {
    source: '03-Food-Images/shish-tauk-turkish.jpg',
    sourceKind: 'reference',
  },
  'persian-style-lamb-chops': {
    source: '03-Food-Images/persian-style-lamb-chops.jpg',
    sourceKind: 'own',
  },
  'turkish-lamb-cheese-kebab': {
    source: '03-Food-Images/turkish-lamb-cheese-kebab.jpg',
    sourceKind: 'reference',
  },
  'jooje-khaas-kebab': {
    source: '03-Food-Images/jooje-khaas-kebab.jpg',
    sourceKind: 'reference',
  },
  'khafif-jooje': {
    source: '03-Food-Images/khafif-jooje.jpg',
    sourceKind: 'reference',
  },
  'adana-kebab': {
    source: '03-Food-Images/adana-kebab.jpg',
    sourceKind: 'reference',
  },
  'summuc-jooje': {
    source: '03-Food-Images/summuc-jooje.jpg',
    sourceKind: 'reference',
  },
  'afghan-seekh-kebab': {
    source: '03-Food-Images/afghan-seekh-kebab.jpg',
    sourceKind: 'reference',
  },
  'beshghab-e-mix': {
    source: '03-Food-Images/beshghab-e-mix.jpg',
    sourceKind: 'reference',
  },
  'eddys-khaas': {
    source: '03-Food-Images/eddys-khaas.jpg',
    sourceKind: 'reference',
  },
  'mama-mia-pasta': {
    source: '03-Food-Images/mama-mia-pasta.jpg',
    sourceKind: 'reference',
  },
  'penny-arbiata-pasta': {
    source: '03-Food-Images/penny-arbiata-pasta.jpg',
    sourceKind: 'reference',
  },
  'beef-lasagna-pasta': {
    source: '03-Food-Images/beef-lasagna-pasta.jpg',
    sourceKind: 'reference',
  },
  'penne-carbonara-pasta': {
    source: '03-Food-Images/penne-carbonara-pasta.jpg',
    sourceKind: 'reference',
  },
  'aglio-e-olio-pasta': {
    source: '03-Food-Images/aglio-e-olio-pasta.jpg',
    sourceKind: 'reference',
  },
  'caesar-salad': {
    source: '03-Food-Images/caesar-salad.jpg',
    sourceKind: 'reference',
  },
  'quinoa-and-cranberry-salad': {
    source: '03-Food-Images/quinoa-and-cranberry-salad.jpg',
    sourceKind: 'reference',
  },
  'feta-salad': {
    source: '03-Food-Images/feta-salad.jpg',
    sourceKind: 'reference',
  },
  'vietnamese-chicken-salad': {
    source: '03-Food-Images/vietnamese-chicken-salad.jpg',
    sourceKind: 'reference',
  },
  'sautee-beef-salad': {
    source: '03-Food-Images/sautee-beef-salad.jpg',
    sourceKind: 'reference',
  },
  'stuff-chicken-fingers': {
    source: '03-Food-Images/stuff-chicken-fingers.jpg',
    sourceKind: 'reference',
  },
  'assorted-mini-sliders': {
    source: '03-Food-Images/assorted-mini-sliders.jpg',
    sourceKind: 'reference',
  },
  'tempura-prawns': {
    source: '03-Food-Images/tempura-prawns.jpg',
    sourceKind: 'reference',
  },
  'chicken-chipotle-nachos': {
    source: '03-Food-Images/chicken-chipotle-nachos.jpg',
    sourceKind: 'reference',
  },
  'dynamite-prawns': {
    source: '03-Food-Images/dynamite-prawns.jpg',
    sourceKind: 'reference',
  },
  fries: {
    source: '03-Food-Images/fries.jpg',
    sourceKind: 'reference',
  },
  'mini-sliders': {
    source: '03-Food-Images/mini-sliders.jpg',
    sourceKind: 'reference',
  },
  'peri-peri-bites': {
    source: '03-Food-Images/peri-peri-bites.jpg',
    sourceKind: 'reference',
  },
  'chicken-quesadillas': {
    source: '03-Food-Images/chicken-quesadillas.jpg',
    sourceKind: 'reference',
  },
  'loaded-sriracha-fries': {
    source: '03-Food-Images/loaded-sriracha-fries.jpg',
    sourceKind: 'reference',
  },
  'butter-chicken-strips': {
    source: '03-Food-Images/butter-chicken-strips.jpg',
    sourceKind: 'reference',
  },
  'masala-fries': {
    source: '03-Food-Images/masala-fries.jpg',
    sourceKind: 'reference',
  },
  'croissant-and-butter-pudding': {
    source: '03-Food-Images/croissant-and-butter-pudding.jpg',
    sourceKind: 'reference',
  },
  'molten-lava-with-ice-cream': {
    source: '03-Food-Images/molten-lava-with-ice-cream.jpg',
    sourceKind: 'reference',
  },
  'nuts-about-nutella': {
    source: '03-Food-Images/nuts-about-nutella.jpg',
    sourceKind: 'reference',
  },
  'home-made-waffles': {
    source: '03-Food-Images/home-made-waffles.jpg',
    sourceKind: 'reference',
  },
  'home-made-nutella': {
    source: '03-Food-Images/home-made-nutella.jpg',
    sourceKind: 'reference',
  },
  'home-made-lotus': {
    source: '03-Food-Images/home-made-lotus.jpg',
    sourceKind: 'reference',
  },
  'cookie-dough-with-ice-cream': {
    source: '03-Food-Images/cookie-dough-with-ice-cream.jpg',
    sourceKind: 'reference',
  },
  'dessert-of-the-week': {
    source: '03-Food-Images/dessert-of-the-week.jpg',
    sourceKind: 'reference',
  },
  'eddys-signature-chocolate-cake': {
    source: '03-Food-Images/eddys-signature-chocolate-cake.jpg',
    sourceKind: 'reference',
  },
  'seasonal-fresh-juice': {
    source: '04-Drink-Images/seasonal-fresh-juice.jpg',
    sourceKind: 'reference',
  },
  'fresh-lime': {
    source: '04-Drink-Images/fresh-lime.jpg',
    sourceKind: 'reference',
  },
  'mint-margarita': {
    source: '04-Drink-Images/mint-margarita.jpg',
    sourceKind: 'reference',
  },
  'blue-lagoon': {
    source: '04-Drink-Images/blue-lagoon.jpg',
    sourceKind: 'reference',
  },
  lime: {
    source: '04-Drink-Images/homemade-sodas-lime.jpg',
    sourceKind: 'reference',
  },
  'strawberry-soda': {
    source: '04-Drink-Images/strawberry-soda.jpg',
    sourceKind: 'reference',
  },
  'strawberry-mint-margarita': {
    source: '04-Drink-Images/strawberry-mint-margarita.jpg',
    sourceKind: 'reference',
  },
  peach: {
    source: '04-Drink-Images/homemade-sodas-peach.jpg',
    sourceKind: 'reference',
  },
  lychee: {
    source: '04-Drink-Images/homemade-sodas-lychee.jpg',
    sourceKind: 'reference',
  },
  raspberry: {
    source: '04-Drink-Images/homemade-sodas-raspberry.jpg',
    sourceKind: 'reference',
  },
  'english-breakfast-tea': {
    source: '04-Drink-Images/english-breakfast-tea.jpg',
    sourceKind: 'reference',
  },
  'cardamom-tea': {
    source: '04-Drink-Images/cardamom-tea.jpg',
    sourceKind: 'reference',
  },
  'chai-tea-latte': {
    source: '04-Drink-Images/chai-tea-latte.jpg',
    sourceKind: 'reference',
  },
  'green-tea': {
    source: '04-Drink-Images/green-tea.jpg',
    sourceKind: 'reference',
  },
  'peach-iced-tea': {
    source: '04-Drink-Images/peach-iced-tea.jpg',
    sourceKind: 'reference',
  },
  'lemon-and-mint-iced-tea': {
    source: '04-Drink-Images/lemon-and-mint-iced-tea.jpg',
    sourceKind: 'reference',
  },
  'strawberry-iced-tea': {
    source: '04-Drink-Images/strawberry-iced-tea.jpg',
    sourceKind: 'reference',
  },
  'hot-espresso': {
    source: '04-Drink-Images/hot-espresso.jpg',
    sourceKind: 'reference',
  },
  'hot-cafe-latte': {
    source: '04-Drink-Images/hot-cafe-latte.jpg',
    sourceKind: 'reference',
  },
  'hot-mocha-latte': {
    source: '04-Drink-Images/hot-mocha-latte.jpg',
    sourceKind: 'reference',
  },
  'hot-vanilla-latte': {
    source: '04-Drink-Images/hot-vanilla-latte.jpg',
    sourceKind: 'reference',
  },
  'hot-white-chocolate-mocha': {
    source: '04-Drink-Images/hot-white-chocolate-mocha.jpg',
    sourceKind: 'reference',
  },
  'hot-spanish-latte': {
    source: '04-Drink-Images/hot-spanish-latte.jpg',
    sourceKind: 'reference',
  },
  'hot-macchiato': {
    source: '04-Drink-Images/hot-macchiato.jpg',
    sourceKind: 'reference',
  },
  'hot-americano': {
    source: '04-Drink-Images/hot-americano.jpg',
    sourceKind: 'reference',
  },
  'hot-cappuccino': {
    source: '04-Drink-Images/hot-cappuccino.jpg',
    sourceKind: 'reference',
  },
  'hot-caramel-latte': {
    source: '04-Drink-Images/hot-caramel-latte.jpg',
    sourceKind: 'reference',
  },
  'hot-hazelnut-latte': {
    source: '04-Drink-Images/hot-hazelnut-latte.jpg',
    sourceKind: 'reference',
  },
  'hot-chocolate': {
    source: '04-Drink-Images/hot-chocolate.jpg',
    sourceKind: 'reference',
  },
  'hot-babychino': {
    source: '04-Drink-Images/hot-babychino.jpg',
    sourceKind: 'reference',
  },
  'iced-cafe-latte': {
    source: '04-Drink-Images/iced-cafe-latte.jpg',
    sourceKind: 'reference',
  },
  'iced-mocha-latte': {
    source: '04-Drink-Images/iced-mocha-latte.jpg',
    sourceKind: 'reference',
  },
  'iced-vanilla-latte': {
    source: '04-Drink-Images/iced-vanilla-latte.jpg',
    sourceKind: 'reference',
  },
  'iced-white-chocolate-mocha': {
    source: '04-Drink-Images/iced-white-chocolate-mocha.jpg',
    sourceKind: 'reference',
  },
  'iced-spanish-latte': {
    source: '04-Drink-Images/iced-spanish-latte.jpg',
    sourceKind: 'reference',
  },
  'iced-cappuccino': {
    source: '04-Drink-Images/iced-cappuccino.jpg',
    sourceKind: 'reference',
  },
  'iced-caramel-latte': {
    source: '04-Drink-Images/iced-caramel-latte.jpg',
    sourceKind: 'reference',
  },
  'iced-hazelnut-latte': {
    source: '04-Drink-Images/iced-hazelnut-latte.jpg',
    sourceKind: 'reference',
  },
  'fruity-chillers-mango': {
    source: '04-Drink-Images/fruity-chillers-mango.jpg',
    sourceKind: 'reference',
  },
  'fruity-chillers-blueberry': {
    source: '04-Drink-Images/fruity-chillers-blueberry.jpg',
    sourceKind: 'reference',
  },
  'fruity-chillers-strawberry': {
    source: '04-Drink-Images/fruity-chillers-strawberry.jpg',
    sourceKind: 'reference',
  },
  'fruity-chillers-mix-berry': {
    source: '04-Drink-Images/fruity-chillers-mix-berry.jpg',
    sourceKind: 'reference',
  },
  'fruity-smoothies-mango': {
    source: '04-Drink-Images/fruity-smoothies-mango.jpg',
    sourceKind: 'reference',
  },
  'fruity-smoothies-blueberry': {
    source: '04-Drink-Images/fruity-smoothies-blueberry.jpg',
    sourceKind: 'reference',
  },
  'fruity-smoothies-strawberry': {
    source: '04-Drink-Images/fruity-smoothies-strawberry.jpg',
    sourceKind: 'reference',
  },
  'fruity-smoothies-mix-berry': {
    source: '04-Drink-Images/fruity-smoothies-mix-berry.jpg',
    sourceKind: 'reference',
  },
  'caramel-shake': {
    source: '04-Drink-Images/caramel-shake.jpg',
    sourceKind: 'reference',
  },
  'oreo-and-cream-shake': {
    source: '04-Drink-Images/oreo-and-cream-shake.jpg',
    sourceKind: 'reference',
  },
  'oreo-strawberry-shake': {
    source: '04-Drink-Images/oreo-strawberry-shake.jpg',
    sourceKind: 'reference',
  },
  'vanilla-shake': {
    source: '04-Drink-Images/vanilla-shake.jpg',
    sourceKind: 'reference',
  },
  'chocolate-shake': {
    source: '04-Drink-Images/chocolate-shake.jpg',
    sourceKind: 'reference',
  },
  'caramel-frappe': {
    source: '04-Drink-Images/caramel-frappe.jpg',
    sourceKind: 'reference',
  },
  'cookies-and-cream-frappe': {
    source: '04-Drink-Images/cookies-and-cream-frappe.jpg',
    sourceKind: 'reference',
  },
  'mocha-frappe': {
    source: '04-Drink-Images/mocha-frappe.jpg',
    sourceKind: 'reference',
  },
  'vanilla-frappe': {
    source: '04-Drink-Images/vanilla-frappe.jpg',
    sourceKind: 'reference',
  },
  'voltage-frappe': {
    source: '04-Drink-Images/voltage-frappe.jpg',
    sourceKind: 'reference',
  },
  'lotus-frappe': {
    source: '04-Drink-Images/lotus-frappe.jpg',
    sourceKind: 'reference',
  },
  'poched-egg': {
    source: '03-Food-Images/poched-egg.jpg',
    sourceKind: 'own',
  },
  'hunter-beef-and-egg-sando': {
    source: '03-Food-Images/hunter-beef-and-egg-sando.jpg',
    sourceKind: 'own',
  },
}
